[build]
  publish = "public"  # Directory to deploy
  command = "hugo"    # Build command

[context.production]
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[build.environment]
  HUGO_VERSION = "0.140.2"  # Set to your Hugo version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self';"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
