[build]
publish = "/public"
command = "hugo server"

[build.environment]
HUGO_VERSION = "0.142.0"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

